template_code = """

/*
 * В C указатели и массивы тесно связаны.
 * Поскольку мы уже немного знакомы с массивами, сосредоточимся на аспекте указателей.
 *
 * Имя массива в выражениях преобразуется в указатель на его первый элемент.
 * Арифметика указателей учитывает размер типа данных (для int обычно 4 байта).
 */

int main() {
    int a[3] = { $$val1$$, $$val2$$, $$val3$$ };
    int *p = a;  // Эквивалентно int *p = &a[0]

    /* Теперь, когда p указывает на массив, мы можем:
     * 1. Обращаться к элементам через разыменование указателя
     * 2. Использовать арифметику указателей
     * 3. Использовать синтаксис массива с указателем
     */

    // Проверка первого элемента через разыменование указателя
    if (*p != {[1]}) {
        return 1;
    }
    
    // Проверка второго элемента через арифметику указателей
    if (*(p + 1) != {[2]}) {
        return 2;
    }
    
    // Проверка третьего элемента через синтаксис массива
    if (p[2] != {[3]}) {
        return 3;
    }

    /*
     * Разница между указателями:
     * - В байтах (при приведении к long)
     * - В элементах массива (разница указателей)
     */
    int *p1 = &a[0];
    int *p2 = &a[1];
    long byte_diff = (long)p2 - (long)p1;  // Разница в байтах
    int int_diff = p2 - p1;               // Разница в элементах
    
    // Проверка разницы адресов в байтах
    if (byte_diff != {[4]}) {
        return 4;
    }
    
    // Проверка разницы в элементах массива
    if (int_diff != {[5]}) {
        return 5;
    }

    return 0;
}
"""

template_condition = "Заполните пропущенные значения, чтобы программа завершилась с кодом 0. Учтите: разница между адресами элементов массива типа int равна размеру int (обычно 4 байта)."

ban_words = ["exit", "return", "[", "goto", "malloc"]

[[error_messages]]
"1" = "Неверное значение первого элемента массива при разыменовании указателя"
"2" = "Неверное значение второго элемента при арифметике указателей"
"3" = "Неверное значение третьего элемента при обращении через синтаксис массива"
"4" = "Некорректная разница между адресами в байтах"
"5" = "Некорректная разница между указателями в элементах массива"