template_code = """
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
    
int main() {
    /*
     * Сравнение размеров строковых массивов:
     * 1. string1 - массив, инициализированный строковым литералом $$string_array_4$$
     * 2. string2 - массив, инициализированный строковым литералом $$string_4$$
     * 3. sizeof возвращает полный размер массива в байтах (включая нуль-терминатор)
     */

    // Инициализация массивов символов
    char string1[] = $$string_array_4$$;  // Массив с автоматическим определением размера
    char string2[] = $$string_4$$;        // Массив с автоматическим определением размера
    
    /*
     * Сравнение размеров массивов:
     * - sizeof(string1) возвращает размер всего массива в байтах
     * - Включает все символы + нуль-терминатор
     * - {[1]} должно быть оператором сравнения (==, !=, <, > и т.д.)
     */
    if (sizeof(string1) {[1]} sizeof(string2))
        return 1;  // Ошибка: условие сравнения размеров не выполнено

    return 0;
}
"""

template_condition = "Заполните пропущенные значения так, чтобы программа завершилась с кодом 0."

ban_words = ["exit", "return", "[", "goto", "malloc", "free", "strlen"]

[[error_messages]]
"1" = "Некорректное сравнение размеров массивов"
"2" = "Неверный размер одного из массивов"
"3" = "Ошибка в определении размера массива (учтите нуль-терминатор)"
"4" = "Неверный оператор сравнения"
