template_code = """
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
    
/*
* Работа с C-строками (массивами символов):
* 1. Строка инициализируется литералом $$string_3$$
* 2. Изменение символов разными способами:
*    - Через индекс массива []
*    - Через арифметику указателей *
*    - Комбинированным способом
* 3. Проверка результата после каждого изменения
*/

int main() {
    // Инициализация строки (автоматически добавляется нуль-терминатор)
    char string[] = $$string_3$$;

    // Способ 1: изменение через индекс массива
    string[$$index_3_1$$] = $$char_3_1$$;
    if (strcmp({[1]}, string) != 0)
        return 1;  // Ошибка после первого изменения
    
    // Способ 2: изменение через арифметику указателей
    *(string + $$index_3_2$$) = $$char_3_2$$;
    if (strcmp({[2]}, string) != 0)
        return 2;  // Ошибка после второго изменения
    
    // Способ 3: комбинированный доступ
    (string + $$index_3_3$$)[$$index_3_4$$] = $$char_3_3$$;
    if (strcmp({[3]}, string) != 0)
        return 3;  // Ошибка после третьего изменения

    return 0;
}
"""

template_condition = "Заполните пропущенные значения так, чтобы программа завершилась с кодом 0."

ban_words = ["exit", "return", "[", "goto", "malloc", "free"]

[[error_messages]]
"1" = "Неверное состояние строки после первого изменения (индексный доступ)"
"2" = "Неверное состояние строки после второго изменения (арифметика указателей)"
"3" = "Неверное состояние строки после третьего изменения (комбинированный доступ)"
"4" = "Выход за границы строки при модификации"