template_code = """
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
    
int main() {
    // Test 7: function_paramater
    char string[] = $$func_param_string_7$$;
    
    if ({[1]} != sizeof(string))
        return 1;

    return 0;
}
"""

template_condition = "Заполните пропущенные значения переменных таким образом, чтобы программа завершалась с кодом 0."


ban_words = ["exit", ";", "return", "["]
