template_code = """
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

/*
* Основные операции со строками:
* - Проверка на NULL
* - Доступ к первому символу
* - Доступ к символу по смещению
* - Работа с указателями и разыменованием
*/

int main() {
    // Инициализация строки
    char *string = $$string_1$$;
    
    // Проверка что указатель не NULL
    if (string {[1]} NULL)
        return 1;
    
    // Проверка первого символа
    if ({[2]} != *string)
        return 1;
    
    // Проверка символа по смещению
    if ({[3]} != *(string + $$index_1$$))
        return 1;

    return 0;
}
"""

template_condition = "Заполните пропущенные значения переменных таким образом, чтобы программа завершалась с кодом 0."

ban_words = ["exit", "return", "[", "goto", "malloc", "free", "strcpy", "memcpy"]

[[error_messages]]
"1" = "Некорректная проверка указателя на NULL"
"2" = "Первый символ строки не соответствует ожидаемому"
"3" = "Символ по указанному смещению неверный"
"4" = "Выход за границы строки при доступе"