template_code = """
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/*
* Анализ строковых параметров:
* 1. Инициализация строкового массива
* 2. Проверка размера массива
* 
* Ключевые моменты:
* - sizeof возвращает полный размер массива в байтах
* - Включает нуль-терминатор
* - Размер фиксирован на этапе компиляции
*/

int main() {
    // Инициализируем строковый массив
    char string[] = $$func_param_string_7$$;
    
    // Проверяем размер массива
    if ({[1]} != sizeof(string))
        return 1;

    return 0;
}
"""

template_condition = "Заполните пропущенные значения переменных таким образом, чтобы программа завершалась с кодом 0."


ban_words = ["exit", "return", "[", "strlen"]

[[error_messages]]
"1" = "Размер массива не соответствует ожидаемому"
"2" = "Неверный расчет размера строки с учетом нуль-терминатора"
