template_code = """

static int static_function(int);

int global_var = $$global_val$$;

int modify_global()
{
    /*
    * Глобальные переменные:
    * - Видны всей программе
    * - Инициализируются нулем по умолчанию
    * - Существуют в течение всего времени выполнения программы
    * - Располагаются в сегменте данных
    */
    global_var += $$global_plus$$;
    return global_var;
}

int modify_local()
{
    /*
    * Локальные (автоматические) переменные:
    * - Видны только внутри функции
    * - Не инициализируются по умолчанию
    * - Создаются при каждом вызове функции
    * - Располагаются в стеке
    */
    int i = $$local_val$$;
    i += $$local_plus$$;
    return i;
}

int modify_local_static()
{
    /*
    * Статические локальные переменные:
    * - Видны только внутри функции
    * - Инициализируются один раз при первом вызове
    * - Сохраняют значение между вызовами
    * - Располагаются в сегменте данных
    */
    static int i = $$static_val$$;
    i += $$static_plus$$;
    static_function(0);
    return i;
}

int main() {
    /*
    * Области видимости в C:
    * 1. Глобальные переменные - доступны везде после объявления
    * 2. Локальные переменные - доступны только внутри блока
    * 3. Static локальные - сохраняют состояние между вызовами
    * 4. Static глобальные - видны только в текущем файле
    */

    // Проверка глобальной переменной (3 изменения)
    modify_global();
    modify_global();
    if (modify_global() != {[1]}) {
        return 1;
    }

    // Проверка локальной переменной (3 вызова, но каждый раз новая)
    modify_local();
    modify_local();
    if (modify_local() != {[2]}) {
        return 2;
    }

    // Проверка static локальной (сохраняет состояние между вызовами)
    modify_local_static();
    modify_local_static();
    if (modify_local_static() != {[3]}) {
        return 3;
    }

    return 0;
}

/*
* Static функции:
* - Видны только в текущем файле
* - Позволяют скрыть реализацию от других модулей
*/
static int static_int = $$static_val_func$$;

static int static_function(int n)
{
    static_int += $$static_plus_func$$;
    if (n == 0)
        return 0;
    else
        return static_int + static_function(n - 1);
}
"""

template_condition = "Заполните значения переменных так, чтобы программа завершалась с кодом 0, учитывая особенности областей видимости."

ban_words = ["exit", ";", "return", "[", "goto"]

[[error_messages]]
"1" = "Некорректное значение глобальной переменной после изменений"
"2" = "Локальная переменная не была правильно проинициализирована"
"3" = "Static локальная переменная не сохранила состояние между вызовами"
"4" = "Ошибка в работе static функции"
"5" = "Некорректное значение static глобальной переменной"